<?php

require_once "../problem_3c.php";

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-06-02 at 11:57:37.
 */
class MainTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Main
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Main();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Main::isPreparedPrime
     * @todo   Implement testIsPreparedPrime().
     */
    public function testIsPreparedPrime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::getPreparedFactor
     * @todo   Implement testGetPreparedFactor().
     */
    public function testGetPreparedFactor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::isMillerRabinPrime
     * @todo   Implement testIsMillerRabinPrime().
     */
    public function testIsMillerRabinPrime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::isFermatPrime
     * @todo   Implement testIsFermatPrime().
     */
    public function testIsFermatPrime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::factorBrent
     * @todo   Implement testFactorBrent().
     */
    public function testFactorBrent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::gmp_min
     * @todo   Implement testGmp_min().
     */
    public function testGmp_min() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::gmp_rand
     * @todo   Implement testGmp_rand().
     */
    public function testGmp_rand() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::getBrent
     * @todo   Implement testGetBrent().
     */
    public function testGetBrent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::gmp_modsqrt
     * @todo   Implement testGmp_modsqrt().
     */
    public function testGmp_modsqrt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::gmp_modinv
     * @todo   Implement testGmp_modinv().
     */
    public function testGmp_modinv() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::array_xor
     * @todo   Implement testArray_xor().
     */
    public function testArray_xor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::gmp_sort
     * @todo   Implement testGmp_sort().
     */
    public function testGmp_sort() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::getNextPrime
     * @todo   Implement testGetNextPrime().
     */
    public function testGetNextPrime() {
        // Remove the following lines when you implement this test.
        $nextVal = gmp_strval(Main::getNextPrime(gmp_init("1000000000000000000000000000000000000000000000000000000000000")));
        $this->assertEquals("1000000000000000000000000000000000000000000000000000000000007", $nextVal);
    }

    /**
     * @covers Main::knuth
     * @todo   Implement testKnuth().
     */
    public function testKnuth() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::factor
     * @todo   Implement testFactor().
     */
    public function testFactor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Main::main
     * @todo   Implement testMain().
     */
    public function testMain() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
